new_map = {
    'Mario finish line': 'F',
    'Spiky': 'y',
    'Goomba': 'g',
    'Winged Goomba': 'G',
    'Green Koopa': 'k',
    'Winged Green Koopa': 'K',
    'Red Koopa': 'r',
    'Winged Red Koopa': 'R',
    'Ground Block': 'X',
    'Pyramind Block': '#',
    'Bullet bill head': 'B',
    'Bullet bill neck or body': 'b',
    'Special Question block': '?',
    'Coin Question block': '!',
    'Invisible 1 up block': '1',
    'Invisible coin block': '2',
    'Normal Brick Block': 'S',
    'Coin Brick Block': 'C',
    'Mushroom Brick Block': 'U',
    '1 up Block': 'L',
    'Coin': 'o',
    'Empty Pipe': 't',
    'Pipe with Piranaha Plant in it': 'T'
}
