from transformers import pipeline
from mario_gpt.instructions import adapter_instructions, splitter_instruction
from mario_gpt.prompter import Prompter
import torch
import random


class PromptAdapter:
    def __init__(self, llm, prompter: Prompter = None, DEFAULT_MODEL: str = "llama-3.1-8b-instant"):
        """
        Initialize the PromptAdapter class with a specified LLM model.

        :param model_name: The name of the language model to use for adaptation.
        :param prompter: An optional instance of the Prompter class.
        """
        if not llm:
            raise ValueError("A valid LLM instance must be provided.")
        self.llm = llm
        self.prompter_base = prompter or Prompter()  
        self.DEFAULT_MODEL = DEFAULT_MODEL
        self.prefixes = [
            "Generate levels with",
            "Create a level that has",
            "Design a level with",
            "Make a level that includes",
            "Produce a level featuring",
            "I want a level that has",
            "I want a level with",
            "Craft a level that includes",
            "Build a level featuring",
            "Design a level around",
            "I need a level that has",
            "Create a level featuring",
            "Generate a level with",
            "Give me a level that includes",
            "Make a level with",
            "I want to see a level that includes",
            "Please generate a level with",
            "I would like a level that has",
            "Construct a level featuring"
        ]

    def remove_keyword(self, prompt: str) -> str:
        pairs = [pair.strip() for pair in prompt.split(',')]

        # Prob dist map
        removal_options = [
            (2, 7),    # 2% chance for 7 removals
            (4, 6),    # 4% chance for 6 removals
            (4, 5),    # 4% chance for 5 removals
            (6, 4),    # 6% chance for 4 removals
            (10, 1),    # 10% chance for 1 removal
            (10, 2),    # 10% chance for 2 removals
            (10, 3),    # 10% chance for 3 removals
        ]

        rand = random.random() * 100  
        for prob, num_to_remove in removal_options:
            if rand <= prob:
                pairs = random.sample(pairs, len(pairs) - num_to_remove)
                break
            
        return ', '.join(pairs)

    def prompt_adapter_instruction(self, instruction: str, input_text: str) -> str:
        """
        Returns a formatted instruction for the prompt adapter.

        :param instruction: The instruction template to use.
        :param input_text: The input to include in the instruction.
        :return: A formatted string with the instruction and input.
        """
        return f"""
                ### Instructions:
                {instruction}

                ### Given Prompt:
                {input_text}

                ### Evolved Prompt:
                """

    def adapt_prompt(self, base_prompt: str, use_groq: bool = False) -> str:
        """
        Converts structured prompts into a natural language phrase using the LLM.

        :param prompts: The structured prompt string (e.g., "many pipes, many enemies, some blocks, high elevation").
        :return: A natural language phrase generated by the LLM.
        """
        if not adapter_instructions:
            raise ValueError("Instructions list is empty or not defined.")
        
        base_prompt = self.remove_keyword(base_prompt)
        selected_instruction = random.choice(adapter_instructions)  
        combined_prompts = f"{random.choice(self.prefixes)} {base_prompt}".replace("little", "a few")

        if random.random() >= 0.96: 
            return combined_prompts, combined_prompts

        prompt_for_adapter = self.prompt_adapter_instruction(selected_instruction, combined_prompts)

        if use_groq:
            response = self.llm.chat.completions.create(
                model=self.DEFAULT_MODEL,
                messages=[
                    {"role": "system", "content": "You are a prompt rewriter."},
                    {"role": "user", "content": prompt_for_adapter}
                ],
                temperature=0.7
            )
            return response.choices[0].message.content.strip(), combined_prompts

        generated_text = self.llm(prompt_for_adapter, max_length=1028, num_return_sequences=1)
        return generated_text[0]["generated_text"].strip(), combined_prompts



    def new_prompter(self, level, use_groq: bool = False) -> str:
        """
        Generates a new prompter output based on the given level.

        :param level: The level to generate a prompter output for. Can be a list or a tensor.
        :return: A new prompter output.
        """
        if not hasattr(self.prompter_base, "__call__"):
            raise AttributeError("The Prompter instance must be callable.")

        # Check if level is a list
        if isinstance(level, list):
            tokenized_level = self.prompter_base.level_tokenizer(level, return_tensors="pt")
            level_tensor = tokenized_level['input_ids']
            flattened_tensor = level_tensor.view(-1)
            prompt_base, _, _ = self.prompter_base(level=flattened_tensor)

        # Check if level is already a tensor
        elif isinstance(level, torch.Tensor):
            prompt_base, _, _ = self.prompter_base(level=level)

        else:
            raise TypeError("Level must be either a list or a tensor.")
    
        new_prompt, combined_prompt = self.adapt_prompt(prompt_base, use_groq)

        return new_prompt, prompt_base, combined_prompt
    

class PromptSplitter:
    def __init__(self, llm, max_level_size: int = 4, DEFAULT_MODEL: str = "llama-3.1-8b-instant"):
        if not llm:
            raise ValueError("LLM is required")
        self.llm = llm
        self.max_level_size = max_level_size
        self.DEFAULT_MODEL = DEFAULT_MODEL


    def split_prompt(self, prompt: str, use_groq: bool = False):
        instruction = splitter_instruction.format(prompt=prompt)
    
        if use_groq:
            response = self.llm.chat.completions.create(
                model=self.DEFAULT_MODEL,
                messages=[
                    {"role": "system", "content": "You are a prompt splitter."},
                    {"role": "user", "content": instruction + prompt}
                ],
                temperature=0.7
            )
            output_text = response.choices[0].message.content.strip()
        else:   
            output_text = self.llm(instruction + prompt).strip()

        sections = [line.strip() for line in output_text.split("\n") if line.strip()]
        return [s for s in sections if s.startswith(tuple(f"{i}." for i in range(1, self.max_level_size + 1)))]

    def generate_levels(self, prompt: str, mario_lm) -> list:
        num_sections = self.analyze_prompt_sections(prompt)
        section_prompts = self.split_prompt(prompt, num_sections)
        
        current_level = mario_lm.sample(
            prompts=section_prompts[0],
            num_steps=1400,
            temperature=2.0,
            use_tqdm=True
        )
        
        for prompt in section_prompts[1:]:
            current_level = mario_lm.sample(
                seed=current_level,
                prompts=prompt,
                num_steps=1400,
                temperature=2.0,
                use_tqdm=True
            )
            
        return current_level