from transformers import pipeline
from mario_gpt.instructions import instructions  
from mario_gpt.prompter import Prompter
import random


class PromptAdapter:
    def __init__(self, model_name: str = "meta-llama/Llama-3.1-8B-Instruct", prompter: Prompter = None):
        """
        Initialize the PromptAdapter class with a specified LLM model.

        :param model_name: The name of the language model to use for adaptation.
        :param prompter: An optional instance of the Prompter class.
        """
        self.llm = pipeline("text-generation", model=model_name)
        self.prompter_base = prompter or Prompter()  

        self.prefixes = [
            "Generate levels with",
            "Create a level that has",
            "Design a level with",
            "Make a level that includes",
            "Produce a level featuring",
            "I want a level that has",
            "I want a level with",
            "Craft a level that includes",
            "Build a level featuring",
            "Design a level around",
            "I need a level that has",
            "Create a level featuring",
            "Generate a level with",
            "Give me a level that includes",
            "Make a level with",
            "I want to see a level that includes",
            "Please generate a level with",
            "I would like a level that has",
            "Construct a level featuring"
        ]

    def prompt_adapter_instruction(self, instruction: str, input_text: str) -> str:
        """
        Returns a formatted instruction for the prompt adapter.

        :param instruction: The instruction template to use.
        :param input_text: The input to include in the instruction.
        :return: A formatted string with the instruction and input.
        """
        return f"""
                {instruction}

                ### Given Prompt:
                {input_text}

                ### Evolved Prompt:
                """

    def adapt_prompt(self, base_prompt: str) -> str:
        """
        Converts structured prompts into a natural language phrase using the LLM.

        :param prompts: The structured prompt string (e.g., "many pipes, many enemies, some blocks, high elevation").
        :return: A natural language phrase generated by the LLM.
        """
        if not instructions:
            raise ValueError("Instructions list is empty or not defined.")
        
        selected_instruction = random.choice(instructions)  
        combined_prompts = f"{random.choice(self.prefixes)} {base_prompt}"

        prompt_for_adapter = self.prompt_adapter_instruction(selected_instruction, combined_prompts)
        generated_text = self.llm(prompt_for_adapter, max_length=100, num_return_sequences=1)

        return generated_text[0]["generated_text"].strip()

    def new_prompter(self, level: str) -> str:
        """
        Generates a new prompter output based on the given level.

        :param level: The level to generate a prompter output for.
        :return: A new prompter output.
        """
        if not hasattr(self.prompter_base, "__call__"):
            raise AttributeError("The Prompter instance must be callable.")
        
        prompt_base, _, _, _ = self.prompter_base(level=level)  # Generate the structured prompt
        new_prompt = self.adapt_prompt(prompt_base)

        return new_prompt
