from transformers import pipeline
from mario_gpt.instructions import instructions  
from mario_gpt.prompter import Prompter
import torch
import random


class PromptAdapter:
    def __init__(self, llm, prompter: Prompter = None):
        """
        Initialize the PromptAdapter class with a specified LLM model.

        :param model_name: The name of the language model to use for adaptation.
        :param prompter: An optional instance of the Prompter class.
        """
        if not llm:
            raise ValueError("A valid LLM instance must be provided.")
        self.llm = llm

        self.prompter_base = prompter or Prompter()  

        self.prefixes = [
            "Generate levels with",
            "Create a level that has",
            "Design a level with",
            "Make a level that includes",
            "Produce a level featuring",
            "I want a level that has",
            "I want a level with",
            "Craft a level that includes",
            "Build a level featuring",
            "Design a level around",
            "I need a level that has",
            "Create a level featuring",
            "Generate a level with",
            "Give me a level that includes",
            "Make a level with",
            "I want to see a level that includes",
            "Please generate a level with",
            "I would like a level that has",
            "Construct a level featuring"
        ]

    def prompt_adapter_instruction(self, instruction: str, input_text: str) -> str:
        """
        Returns a formatted instruction for the prompt adapter.

        :param instruction: The instruction template to use.
        :param input_text: The input to include in the instruction.
        :return: A formatted string with the instruction and input.
        """
        return f"""
                {instruction}

                ### Given Prompt:
                {input_text}

                ### Evolved Prompt:
                """

    def adapt_prompt(self, base_prompt: str) -> str:
        """
        Converts structured prompts into a natural language phrase using the LLM.

        :param prompts: The structured prompt string (e.g., "many pipes, many enemies, some blocks, high elevation").
        :return: A natural language phrase generated by the LLM.
        """
        if not instructions:
            raise ValueError("Instructions list is empty or not defined.")
        
        selected_instruction = random.choice(instructions)  
        combined_prompts = f"{random.choice(self.prefixes)} {base_prompt}"

        prompt_for_adapter = self.prompt_adapter_instruction(selected_instruction, combined_prompts)
        generated_text = self.llm(prompt_for_adapter, max_length=1028, num_return_sequences=1)

        return generated_text[0]["generated_text"].strip()

    def new_prompter(self, level: list) -> str:
        """
        Generates a new prompter output based on the given level.

        :param level: The level to generate a prompter output for.
        :return: A new prompter output.
        """
        if not hasattr(self.prompter_base, "__call__"):
            raise AttributeError("The Prompter instance must be callable.")
        
        tokenized_level = self.prompter_base.level_tokenizer(level, return_tensors="pt")

        level_tensor = tokenized_level['input_ids']
        flattened_tensor = level_tensor.view(-1)
        
        prompt_base, _, _, _ = self.prompter_base(level=flattened_tensor)  # Generate the structured prompt
        print(prompt_base)
        new_prompt = self.adapt_prompt(prompt_base)

        return new_prompt
    

class PromptSplitter:
    def __init__(self, llm, max_level_size: int = 4, DEFAULT_MODEL: str = "llama-3.1-3b-preview"):
        if not llm:
            raise ValueError("LLM is required")
        self.llm = llm
        self.max_level_size = max_level_size
        self.DEFAULT_MODEL = DEFAULT_MODEL


    def full_thingy(self, prompt: str, use_groq: bool = False):
        instruction = f"""You are an AI that segments a Mario level generation request into multiple steps, preserving all original information while structuring a logical sequence.

        ### **Guidelines:**
        1. **Determine the correct number of segments internally** – Identify major transitions in difficulty, enemies, obstacles, power-ups, or mechanics. Each major shift should correspond to a new sentence.
        2. **Preserve all original information** – No details from the input prompt should be removed or inferred.
        3. **Maintain logical progression** – If the prompt describes a sequence, each sentence must follow a natural order.
        4. **Carry forward elements when needed** – If a level adds enemies or changes difficulty, ensure previous elements persist unless explicitly replaced.
        5. **Each sentence must be self-contained** – The segments should be complete sentences that make sense independently.
        6. **Strict output format** – Return only the segmented sentences in a structured list format. No explanations or additional text.

        ---

        ### **Examples:**
        #### **Example 1**
        **Input:**  
        Prompt: "Create a level that starts off easy with a couple of powerups and coins, but then ramps up into a difficult level filled with goombas and koopas."

        **Output:**  
        1. "Create a level with a couple of powerups and coins."  
        2. "Create a level filled with goombas and koopas."

        ---

        #### **Example 2**
        **Input:**  
        Prompt: "Generate a level that has some goombas, and starts raising in difficulty adding koopas to the mix, and finally adds all types of enemies."

        **Output:**  
        1. "Generate a level that has some goombas."  
        2. "Generate a difficult level that has goombas and koopas."  
        3. "Generate a difficult level that has all types of enemies, including goombas and koopas."

        ---

        ### **Task**
        Segment the following prompt into the appropriate number of sequential steps while maintaining all information.

        **Input:**  
        Prompt: "{prompt}"  

        **Output:**  
        """
            
        if use_groq:
            response = self.llm.chat.completions.create(
                model=self.DEFAULT_MODEL,
                messages=[
                    {"role": "system", "content": "You are a prompt splitter."},
                    {"role": "user", "content": instruction + prompt}
                ],
                temperature=0.7
            )
            output_text = response.choices[0].message.content.strip()
        else:   
            output_text = self.llm(instruction + prompt).strip()

        sections = [line.strip() for line in output_text.split("\n") if line.strip()]
        return [s for s in sections if s.startswith(tuple(f"{i}." for i in range(1, self.max_level_size + 1)))]

    def generate_levels(self, prompt: str, mario_lm) -> list:
        num_sections = self.analyze_prompt_sections(prompt)
        section_prompts = self.split_prompt(prompt, num_sections)
        
        current_level = mario_lm.sample(
            prompts=section_prompts[0],
            num_steps=1400,
            temperature=2.0,
            use_tqdm=True
        )
        
        for prompt in section_prompts[1:]:
            current_level = mario_lm.sample(
                seed=current_level,
                prompts=prompt,
                num_steps=1400,
                temperature=2.0,
                use_tqdm=True
            )
            
        return current_level